name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      # Configure Pages (sets up the Pages environment)
      - uses: actions/configure-pages@v5

      # Build with env for your form URL
      - run: npm run build
        env:
          VITE_FORM_URL: https://docs.google.com/forms/d/e/1FAIpQLSdORzmzExK0OCnY8RXFQAUQxm5MPEJ6Z_GeLm2oDGKQT-zrwg/viewform?usp=dialog

      # SPA fallback
      - run: cp dist/index.html dist/404.html

      # Upload artifact
      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # (optional — redundant if set at top-level, but safe)
    permissions:
      pages: write
      id-token: write
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
